# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sheets.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sheets.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csheets.proto\x12\x06sheets\"\x07\n\x05\x45mpty\"J\n\x0bTaskRequest\x12\x0c\n\x04task\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x10\n\x08priority\x18\x03 \x01(\t\x12\x0b\n\x03\x64\x61y\x18\x04 \x01(\t\"\x1f\n\x0cTaskResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2q\n\rSheetsService\x12\x34\n\x07\x41\x64\x64Task\x12\x13.sheets.TaskRequest\x1a\x14.sheets.TaskResponse\x12*\n\nClearTasks\x12\r.sheets.Empty\x1a\r.sheets.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sheets_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=24
  _globals['_EMPTY']._serialized_end=31
  _globals['_TASKREQUEST']._serialized_start=33
  _globals['_TASKREQUEST']._serialized_end=107
  _globals['_TASKRESPONSE']._serialized_start=109
  _globals['_TASKRESPONSE']._serialized_end=140
  _globals['_SHEETSSERVICE']._serialized_start=142
  _globals['_SHEETSSERVICE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
