# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.services import youtube_pb2 as youtube__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in youtube_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class YouTubeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTrending = channel.unary_unary(
                '/youtube.YouTubeService/GetTrending',
                request_serializer=youtube__pb2.Empty.SerializeToString,
                response_deserializer=youtube__pb2.TrendingResponse.FromString,
                _registered_method=True)
        self.GetChannelAnalytics = channel.unary_unary(
                '/youtube.YouTubeService/GetChannelAnalytics',
                request_serializer=youtube__pb2.ChannelRequest.SerializeToString,
                response_deserializer=youtube__pb2.AnalyticsResponse.FromString,
                _registered_method=True)


class YouTubeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTrending(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChannelAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YouTubeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTrending': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrending,
                    request_deserializer=youtube__pb2.Empty.FromString,
                    response_serializer=youtube__pb2.TrendingResponse.SerializeToString,
            ),
            'GetChannelAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChannelAnalytics,
                    request_deserializer=youtube__pb2.ChannelRequest.FromString,
                    response_serializer=youtube__pb2.AnalyticsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'youtube.YouTubeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('youtube.YouTubeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class YouTubeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTrending(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/youtube.YouTubeService/GetTrending',
            youtube__pb2.Empty.SerializeToString,
            youtube__pb2.TrendingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChannelAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/youtube.YouTubeService/GetChannelAnalytics',
            youtube__pb2.ChannelRequest.SerializeToString,
            youtube__pb2.AnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
