# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: youtube.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'youtube.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ryoutube.proto\x12\x07youtube\"\x07\n\x05\x45mpty\"$\n\x0e\x43hannelRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\t\"2\n\x10TrendingResponse\x12\x0e\n\x06titles\x18\x01 \x03(\t\x12\x0e\n\x06topics\x18\x02 \x03(\t\"7\n\x11\x41nalyticsResponse\x12\x0e\n\x06growth\x18\x01 \x01(\t\x12\x12\n\ntop_videos\x18\x02 \x03(\t2\x96\x01\n\x0eYouTubeService\x12\x38\n\x0bGetTrending\x12\x0e.youtube.Empty\x1a\x19.youtube.TrendingResponse\x12J\n\x13GetChannelAnalytics\x12\x17.youtube.ChannelRequest\x1a\x1a.youtube.AnalyticsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'youtube_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_CHANNELREQUEST']._serialized_start=35
  _globals['_CHANNELREQUEST']._serialized_end=71
  _globals['_TRENDINGRESPONSE']._serialized_start=73
  _globals['_TRENDINGRESPONSE']._serialized_end=123
  _globals['_ANALYTICSRESPONSE']._serialized_start=125
  _globals['_ANALYTICSRESPONSE']._serialized_end=180
  _globals['_YOUTUBESERVICE']._serialized_start=183
  _globals['_YOUTUBESERVICE']._serialized_end=333
# @@protoc_insertion_point(module_scope)
